return {
	base00 = "{{colors.background}}",
	base01 = "{{colors.surface0}}",
	base02 = "{{colors.surface1}}",
	base03 = "{{colors.surface2}}",
	base04 = "{{colors.text}}",
	base05 = "{{colors.text}}",
	base06 = "{{colors.text}}",
	base07 = "{{colors.text}}",
	base08 = "{{colors.red}}",
	base09 = "{{colors.peach}}",
	base0A = "{{colors.yellow}}",
	base0B = "{{colors.green}}",
	base0C = "{{colors.teal}}",
	base0D = "{{colors.blue}}",
	base0E = "{{colors.mauve}}",
	base0F = "{{colors.pink}}",
}
